### ISSUE TITLE
Needs Review for MVP list #2 User Login/Singup/WelcomePage

### ISSUE THREAD

**Issue by Sokada101** [Sokada101/Catflix#3]
Needs Review for MVP list #2 User Login/Singup/WelcomePage

**Comment by jmeyer90** [comment]
Tasks to complete:

Styling:
- On the sign in page, input fields should be larger.
- Netflix's signup page is more complicated, offering various deals. Your sign up page looks different but I'll make an exception in this case and say it's okay.
- Style email errors to be displayed the same as password errors

Functionality:
- Our pages need a footer at the bottom. This is where we'll have links to our github, linkedIn, etc.
- Our login and signup forms should have a demo user.

**Comment by Sokada101** [comment]
what do you mean by "Style email errors to be displayed the same as password errors" ?

**Comment by Sokada101** [comment]
Oh that one came from the gem... let me delete that lol

**Comment by jmeyer90** [comment]
Okay, sounds good.

**Comment by Sokada101** [comment]
so it turns out it didn't come from the gem... do you have any idea where it came from? lol

**Comment by Sokada101** [comment]
I just fixed everything you asked and deployed it to heroku please let me know if you see anything that I need to make changes!

**Comment by jmeyer90** [comment]
Hi Satomi. This looks great! One thing that can be added in a bonus phase is to have user input persist across an invalid submission. Ex: I put in the wrong email and click submit. Rather than having the email field be wiped clean, it would be good to have the user input still appear. Someone might have been off a single character and shouldn't have to type everything out again. That being said, great job! Feel free to move on to your next MVP.

**Comment by Sokada101** [comment]
Thank you! will fix that part when I get a chance!
